SemestrV/WWW/Lista7/www/config/routes.rb
Rails.application.routes.draw do
  resources :cars
  get 'home/index'
  get 'home/contact'
  get 'home/galerry'
  get 'users/index'
  get 'zad1/typ1'
  get 'zad1/typ2'
  get 'zad1/typ3'
  get 'zad1/typ4'
end

SemestrV/WWW/Lista7/www/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

SemestrV/WWW/Lista7/www/app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  CAR_NUMBER_REGEX = /\A.{2,3}\d{4,6}\z/
  @allowed_fuels = %w(
    P
    ON
    LPG
    EE
  )

  validates :fuel, inclusion: { in: @allowed_fuels }
  validates_format_of :registration_number, with: CAR_NUMBER_REGEX
end

SemestrV/WWW/Lista7/www/app/models/user.rb
class User < ApplicationRecord
end

SemestrV/WWW/Lista7/www/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

SemestrV/WWW/Lista7/www/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:registration_number, :fuel, :name, :year_of_production, :date_of_first_yerestration)
    end
end

SemestrV/WWW/Lista7/www/app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
  end

  def contact
  end

  def galerry
  end
end

SemestrV/WWW/Lista7/www/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
  end
end

SemestrV/WWW/Lista7/www/app/controllers/zad1_controller.rb
# frozen_string_literal: true

class Zad1Controller < ApplicationController
  def typ1
    render html: "Hello"
  end

  def typ2
    render plain: "Hello"
  end

  def typ3
    @book = { id: 1, name: "The Book", author: "John Doe", price: 29.95, active: true }
    respond_to do |format|
      format.html do
      end
      format.xml do
        render xml: @book.to_xml
      end
    end
  end

  def typ4
    @book = { id: 1, name: "The Book", author: "John Doe", price: 29.95, active: true }
    respond_to do |format|
      format.html do
      end
      format.json do
        render json: @book.to_json
      end
    end
  end
end

SemestrV/WWW/Lista7/www/app/helpers/application_helper.rb
module ApplicationHelper
end

SemestrV/WWW/Lista7/www/app/helpers/cars_helper.rb
module CarsHelper
end

SemestrV/WWW/Lista7/www/app/helpers/home_helper.rb
module HomeHelper
end

SemestrV/WWW/Lista7/www/app/helpers/users_helper.rb
module UsersHelper
end

SemestrV/WWW/Lista7/www/app/helpers/zad1_helper.rb
module Zad1Helper
end

SemestrV/WWW/Lista7/www/app/views/cars/_form.html.erb
<div class="form-group col-md-4 col-md-offset-4">
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :registration_number %>
    <%= form.text_field :registration_number, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :fuel %>
    <%= form.text_field :fuel, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :year_of_production %>
    <%= form.number_field :year_of_production, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :date_of_first_yerestration %>
    <%= form.date_select :date_of_first_yerestration, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

SemestrV/WWW/Lista7/www/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

SemestrV/WWW/Lista7/www/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Registration number</th>
      <th>Fuel</th>
      <th>Name</th>
      <th>Year of production</th>
      <th>Date of first yerestration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.registration_number %></td>
        <td><%= car.fuel %></td>
        <td><%= car.name %></td>
        <td><%= car.year_of_production %></td>
        <td><%= car.date_of_first_yerestration %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

SemestrV/WWW/Lista7/www/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

SemestrV/WWW/Lista7/www/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registration number:</strong>
  <%= @car.registration_number %>
</p>

<p>
  <strong>Fuel:</strong>
  <%= @car.fuel %>
</p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Year of production:</strong>
  <%= @car.year_of_production %>
</p>

<p>
  <strong>Date of first yerestration:</strong>
  <%= @car.date_of_first_yerestration %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

SemestrV/WWW/Lista7/www/app/views/home/contact.html.erb
<h1>Kontakt</h1>

SemestrV/WWW/Lista7/www/app/views/home/galerry.html.erb
<h1>Galeria</h1>
<%=image_tag("1.jpg", class: "img-circle", width: "304", height:"236")%>
<%=image_tag("2.jpg", class: "img-circle", width: "304", height:"236")%>
<%=image_tag("3.jpg", class: "img-circle", width: "304", height:"236")%>
<%=image_tag("4.jpg", class: "img-circle", width: "304", height:"236")%>

SemestrV/WWW/Lista7/www/app/views/home/index.html.erb
<h1>Strona Główna</h1>

SemestrV/WWW/Lista7/www/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Www</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

SemestrV/WWW/Lista7/www/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LISTA7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'shared/navbar' %>

     <%= yield %>
  </body>
</html>

SemestrV/WWW/Lista7/www/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
 <div class="container">
  <div class="navbar-header">
    <a class="navbar-brand" href="<%= home_index_path %>">MENU</a>
  </div>
  <ul class="nav navbar-nav">
    <li <%if[params[:controller], params[:action]] == ["home","index"]%> class="active" <% end %>> <%=link_to "Menu", home_index_path%></li>
    <li <%if[params[:controller], params[:action]] == ["home","contact"]%> class="active" <% end %>> <%=link_to "Kontakt", home_contact_path%></li>
    <li <%if[params[:controller], params[:action]] == ["home","galerry"]%> class="active" <% end %>>   <%=link_to "Galeria", home_galerry_path%></li>
  </ul>
 </div>
</nav>

SemestrV/WWW/Lista7/www/app/views/users/index.html.erb
<h1>Users</h1>
<hr />
<table>
  <tr>
    <th>First Name</th>
    <th>Second Name</th>
    <th>Age</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.second_name %></td>
      <td><%= user.age %></td>
    </tr>
  <% end %>
</table>
<hr />
<%= paginate @users %>
<%= page_entries_info @users %>

SemestrV/WWW/Lista7/www/app/views/zad1/typ1.html.erb
<h1>Zad1#typ1</h1>
<p>Find me in app/views/zad1/typ1.html.erb</p>

SemestrV/WWW/Lista7/www/app/views/zad1/typ2.html.erb
<h1>Zad1#typ2</h1>
<p>Find me in app/views/zad1/typ2.html.erb</p>

SemestrV/WWW/Lista7/www/app/views/zad1/typ3.html.erb
<h1>Zad1#typ3</h1>
<p>Find me in app/views/zad1/typ3.html.erb</p>

SemestrV/WWW/Lista7/www/app/views/zad1/typ4.html.erb
<h1>Zad1#typ4</h1>
<p>Find me in app/views/zad1/typ4.html.erb</p>